### ISSUE TITLE
RFE: provide a method that adds all InfoTypes without having to specify them

### ISSUE THREAD

**Issue by henrik-io** [googleapis/java-dlp#34]
It would be great if the Java API for DLP de-identification/redaction had a way of specifying that the client wants to use all available `InfoType` variants without having to first retrieve all available InfoTypes, and then explicitly set them. Something like this would be nice:
```
        InspectConfig inspectConfig = InspectConfig.newBuilder().addAllInfoTypes().build();
```

**Comment by suztomo** [comment]
Closing for obsolete. It seems the workaround (first retrieve all available InfoTypes) exists. 

This repository has moved to github.com/googleapis/google-cloud-java. If this is still an issue, please create a ticket there.
