### ISSUE TITLE
Cloud SQL DLP Proxy Throws Exception with NULL Values

### ISSUE THREAD

**Issue by TheCaneda** [googleapis/java-dlp#937]
Hi, I'm having an issue following this tutorial: https://cloud.google.com/architecture/using-a-dlp-proxy-to-interact-with-cloud-sql

Once the DLP Proxy is running, when I try to query tables that have empty values, I get following exception:

![github_issue_dlp_java](https://user-images.githubusercontent.com/86854152/181823828-42be9418-4ceb-4d52-a15f-01ededf3faa2.png)

Does anybody know some fix to this?

**Comment by Sita04** [comment]
@TheCaneda If the issue still persists, kindly file it in https://github.com/GoogleCloudPlatform/java-docs-samples repository as this repo no longer deals with DLP samples.
